### ISSUE TITLE
FromIterator impl gives a corrupt vacant list

### ISSUE THREAD

**Issue by alecmocatta** [tokio-rs/slab#100]
```rust
fn main() {
    let x: slab::Slab<()> = std::iter::once((1, ())).collect();
}
```
This gives a slab with a corrupt vacant list. Once corrupted, I was hitting this panic https://github.com/tokio-rs/slab/blob/v0.4.3/src/lib.rs#L942

Patching `vacant_list_broken = true;` is a workaround.

**Comment by taiki-e** [comment]
Fixed in v0.4.4.
