### ISSUE TITLE
Including .clippy.toml in crate tarball leads to older clippy versions failing

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/slab#103]
… even on crates that have slab as a dependency. [cargo-diet](https://github.com/the-lean-crate/cargo-diet) might help setting a reasonable include / exclude value in `Cargo.toml` / `[package]`. Otherwises [here](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields)'s the docs for those settings.

**Comment by taiki-e** [comment]
This is definitely a clippy bug, but I would accept the patch to exclude the top-level hidden files/dirs, like [my projects do](https://github.com/taiki-e/cargo-hack/blob/4386b3e8f775f36c493fdbd4d5a4aa977dd44c93/Cargo.toml#L10).
