### ISSUE TITLE
Move unsafe code behind a (enabled by default) feature flag

### ISSUE THREAD

**Issue by notgull** [tokio-rs/slab#121]
I am using this crate in a crate that is `forbid(unsafe_code)`, where I would like to reduce the amount of unsafe code in my dependency tree. The unsafe code currently in this crate could be eliminated.

I propose an `unchecked` feature. When enabled, the `get_unchecked` and other methods that require `unsafe` are exposed. When disabled, this crate becomes `forbid(unsafe_code)`. This feature would be enabled by default to prevent breaking changes.

I am willing to implement this feature myself.

**Comment by taiki-e** [comment]
[features should be additive](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification) and we cannot use features to disable APIs.

**Comment by taiki-e** [comment]
Oh, sorry, you seem to be suggesting an additive feature that is enabled by default. However, note that for users using slab with `default-features = false` the approach you suggest is also a breaking change.

**Comment by taiki-e** [comment]
(At this time there are no plans for 0.5...)

**Comment by Darksonn** [comment]
We are unlikely to have a breaking release any time soon, so your PR would probably sit around for at least a year. Additionally, I don't really think there's any value in a feature like this. None of the internals use unsafe besides the methods that are unsafe to call, so if you don't call those, you aren't using any unsafe code.
