### ISSUE TITLE
Overflow documentation

### ISSUE THREAD

**Issue by sebastianv89** [tokio-rs/slab#125]
The documentation (https://docs.rs/slab/latest/slab/struct.Slab.html) states that panics due to overflow occurs when the capacity overflows `usize`. In reality, it already overflows when the capacity exceeds `isize::MAX` *bytes* (https://doc.rust-lang.org/beta/alloc/vec/struct.Vec.html).

**Comment by Darksonn** [comment]
This was already fixed in #124. It will be visible on the documentation when we make the next release.
