### ISSUE TITLE
Does not compile on Arch Linux due to library version mismatch

### ISSUE THREAD

**Issue by Cornul11** [tokio-rs/slab#126]
Trying to install `slab` using `cargo` on Arch Linux with the latest version of the `hiredis` library fails with the following error:
```
  = note: cc: error while loading shared libraries: libhiredis.so.1.0.0: cannot open shared object file: No such file or directory
```
The problem is that the latest version of `hiredis` provides `libhiredis.so.1.1.0` as opposed to the `1.0.0` version. Are there any other solutions other than downgrading the package?

**Comment by Darksonn** [comment]
Slab doesn't depend on hiredis, so you're doing something wrong. What do you mean by "install" in the first place? Slab isn't a binary, so you can't install it.
