### ISSUE TITLE
Feature Request: swap

### ISSUE THREAD

**Issue by ksqsf** [tokio-rs/slab#64]
Since it's impossible to borrow two mutable references out of one slab, it's necessary to provide something like `std::mem::swap`.

**Comment by carllerche** [comment]
Maybe we should add the ability to get mutable references to multiple slots? :) This would be safe to provide.

**Comment by ksqsf** [comment]
Right, do you have an idea in mind? I can only think of something like `Slab<RefCell<T>>` or something like `.get_multiple_mut(index1, index2)`.

**Comment by carllerche** [comment]
`get2_mut` is probably fine as an initial step... if there is a need to get more than 2, we can evaluate later.

**Comment by tormol** [comment]
This might be relying on implementation details, but should work:

```rust
let mut tmp = slab.remove(index1);
std::mem::swap(&mut slab[index2], &mut tmp);
assert_eq!(slab.insert(tmp), index1);
```
