### ISSUE TITLE
Is get2_unchecked_mut redundant?

### ISSUE THREAD

**Issue by Ralith** [tokio-rs/slab#81]
It's unclear to me why this should ever be preferred over calling `get_unchecked` twice. Can we avoid maintaining an extra interface here?

**Comment by hawkw** [comment]
`get_unchecked_mut` mutably borrows the `Slab`, so the interface doesn't permit mutably borrowing a second item while one is already borrowed. `get2_unchecked_mut` can be used to mutate two entries at a time (such as `mem::swap`ping them).

**Comment by Ralith** [comment]
Fair enough!

**Comment by hawkw** [comment]
I notice the docs for `get2_mut` explain the use-case for it:
https://github.com/tokio-rs/slab/blob/3340fdcf7204584b9ee509beabf3b174a333dfc1/src/lib.rs#L693-L709
but the docs for `get2_unchecked_mut` don't, really:
https://github.com/tokio-rs/slab/blob/3340fdcf7204584b9ee509beabf3b174a333dfc1/src/lib.rs#L783-L787

Maybe we could make this a little clearer by having the doc comment for `get2_unchecked_mut` explain the intended use-case, or adding a "This is a version of [`get2_mut`] that doesn't perform bounds and safety condition checks" or something?
